// Generated by https://quicktype.io

import { Chain } from "./evolution-full";
import { Species } from "./pokemon-full";

export interface IChainPokemon {
    baby_trigger_item: null;
    chain:             Chain;
    id:                number;
}


export interface EvolutionDetail {
    gender:                  null;
    held_item:               Species | null;
    item:                    Species | null;
    known_move:              null;
    known_move_type:         null;
    location:                null;
    min_affection:           null;
    min_beauty:              null;
    min_happiness:           null;
    min_level:               number | null;
    needs_overworld_rain:    boolean;
    party_species:           null;
    party_type:              null;
    relative_physical_stats: null;
    time_of_day:             string;
    trade_species:           null;
    trigger:                 Species;
    turn_upside_down:        boolean;
}

// export interface Species {
//     name: string;
//     url:  string;
// }
